"""工具基类与 @tool_action 展开 — 供 ReAct / 未来 Function Calling 复用。"""

from __future__ import annotations

import inspect
import re
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, List, Optional, get_type_hints

from pydantic import BaseModel, ConfigDict


class UserRefusedError(Exception):
    """用户拒绝执行工具操作时抛出，用于通知 Agent 暂停当前循环。"""

    def __init__(self, tool_name: str, detail: str = ""):
        self.tool_name = tool_name
        self.detail = detail
        super().__init__(f"用户拒绝执行工具 {tool_name}: {detail}")


def tool_action(name: Optional[str] = None, description: Optional[str] = None):
    """装饰器：将类方法标记为可展开子工具（expandable=True 时由 get_expanded_tools 收集）。"""

    def decorator(func: Callable) -> Callable:
        func._is_tool_action = True  # type: ignore[attr-defined]
        func._tool_name = name
        func._tool_description = description
        return func

    return decorator


class ToolParameter(BaseModel):
    """工具参数定义（JSON Schema 风格 type 字符串）。"""

    model_config = ConfigDict(extra="forbid")

    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


class Tool(ABC):
    """工具基类：单一工具或可展开为多个子工具。

    安全元数据（参考 Claude Code `buildTool()` 的设计）：所有"风险"相关方法
    默认按最保守（fail-closed）假设返回 False —— 子类显式声明 True 才放开。
    这样工具作者忘记声明也不会引入风险。
    """

    # 简短能力描述（≤10 词），未来可用于 ToolSearch 关键词匹配。
    search_hint: str = ""

    # 是否默认对 LLM 可见。False 表示工具必须通过 `tool_search` 发现后才注入 schema，
    # 用于压缩超大工具集的上下文体积（参考 Claude Code 的"按需暴露"模式）。
    always_visible: bool = True

    def __init__(self, name: str, description: str, expandable: bool = False):
        self.name = name
        self.description = description
        self.expandable = expandable

    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> str:
        """执行工具，返回面向模型/用户的文本结果。"""

    @abstractmethod
    def get_parameters(self) -> List[ToolParameter]:
        """返回参数模式列表。"""

    # ── 安全元数据（默认 fail-closed）──

    def is_enabled(self) -> bool:
        """工具是否在当前环境下可用。默认始终启用。"""
        return True

    def is_read_only(self, parameters: Optional[Dict[str, Any]] = None) -> bool:
        """是否为只读操作。默认假设会写入（fail-closed）。"""
        return False

    def is_concurrency_safe(self, parameters: Optional[Dict[str, Any]] = None) -> bool:
        """是否可与其他并发安全工具并行执行。默认假设不安全（fail-closed）。"""
        return False

    def is_destructive(self, parameters: Optional[Dict[str, Any]] = None) -> bool:
        """是否为不可逆/破坏性操作。被 ToolRegistry 用于兜底确认。默认 False。"""
        return False

    def get_expanded_tools(self) -> Optional[List[Tool]]:
        """可展开工具：从带 @tool_action 的方法生成子工具。"""
        if not self.expandable:
            return None

        tools: List[Tool] = []
        for _attr_name, method in inspect.getmembers(self, predicate=inspect.ismethod):
            fn = getattr(method, "__func__", method)
            if not getattr(fn, "_is_tool_action", False):
                continue
            tools.append(
                AutoGeneratedTool(
                    parent=self,
                    method=method,
                    name=getattr(fn, "_tool_name", None),
                    description=getattr(fn, "_tool_description", None),
                )
            )
        return tools if tools else None

    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        required = [p.name for p in self.get_parameters() if p.required]
        return all(k in parameters for k in required)

    def to_dict(self) -> Dict[str, Any]:
        params = [p.model_dump() for p in self.get_parameters()]
        params.append(
            ToolParameter(
                name="confirm",
                type="boolean",
                description="是否在执行前询问用户确认。true=确认，false=直接执行；不传时使用全局默认。",
                required=False,
            ).model_dump()
        )
        return {
            "name": self.name,
            "description": self.description,
            "parameters": params,
        }

    def to_openai_schema(self) -> Dict[str, Any]:
        """OpenAI Chat Completions `tools` 用的 function schema。"""
        parameters = self.get_parameters()
        properties: Dict[str, Any] = {}
        required: List[str] = []

        for param in parameters:
            prop: Dict[str, Any] = {
                "type": param.type,
                "description": param.description,
            }
            if param.default is not None:
                prop["description"] = f"{param.description} (默认: {param.default})"
            if param.type == "array":
                prop["items"] = {"type": "string"}
            properties[param.name] = prop
            if param.required:
                required.append(param.name)

        # 框架级参数：所有工具统一支持每次调用是否确认。
        properties["confirm"] = {
            "type": "boolean",
            "description": "是否在执行前询问用户确认。true=确认，false=直接执行；不传时使用全局默认。",
        }

        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                },
            },
        }

    def __str__(self) -> str:
        return f"Tool(name={self.name})"

    def __repr__(self) -> str:
        return self.__str__()


class AutoGeneratedTool(Tool):
    """由 @tool_action 方法自动生成的子工具。"""

    def __init__(
        self,
        parent: Tool,
        method: Callable,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        self.parent = parent
        self.method = method
        fn = getattr(method, "__func__", method)

        if name is None:
            method_name = getattr(fn, "__name__", "action").lstrip("_")
            name = f"{parent.name}_{method_name}"

        if description is None:
            description = self._extract_description_from_docstring()

        super().__init__(name=name, description=description, expandable=False)
        self._parameters = self._parse_parameters()

    def _extract_description_from_docstring(self) -> str:
        fn = getattr(self.method, "__func__", self.method)
        doc = inspect.getdoc(fn)
        if not doc:
            return f"执行 {getattr(fn, '__name__', 'method')}"
        for line in doc.split("\n"):
            line = line.strip()
            if line and not line.startswith("Args:") and not line.startswith("Returns:"):
                return line
        return f"执行 {getattr(fn, '__name__', 'method')}"

    def _parse_parameters(self) -> List[ToolParameter]:
        fn = getattr(self.method, "__func__", self.method)
        sig = inspect.signature(fn)
        type_hints = get_type_hints(fn)
        docstring = inspect.getdoc(fn) or ""
        param_descriptions = self._parse_param_descriptions(docstring)

        parameters: List[ToolParameter] = []
        for param_name, param in sig.parameters.items():
            if param_name == "self":
                continue
            param_type_hint = type_hints.get(param_name, str)
            param_type = self._python_type_to_tool_type(param_type_hint)
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default
            desc = param_descriptions.get(param_name, f"参数 {param_name}")
            parameters.append(
                ToolParameter(
                    name=param_name,
                    type=param_type,
                    description=desc,
                    required=required,
                    default=default,
                )
            )
        return parameters

    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:
        descriptions: Dict[str, str] = {}
        args_match = re.search(r"Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)", docstring, re.DOTALL)
        if not args_match:
            return descriptions
        args_section = args_match.group(1)
        param_pattern = (
            r"^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)"
        )
        for match in re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL):
            pn = match.group(1).strip()
            pd = re.sub(r"\s+", " ", match.group(2).strip())
            descriptions[pn] = pd
        return descriptions

    def _python_type_to_tool_type(self, py_type: Any) -> str:
        origin = getattr(py_type, "__origin__", None)
        if origin is not None:
            if origin is list:
                return "array"
            if origin is dict:
                return "object"
        type_map = {
            str: "string",
            int: "integer",
            float: "number",
            bool: "boolean",
            list: "array",
            dict: "object",
        }
        return type_map.get(py_type, "string")

    def get_parameters(self) -> List[ToolParameter]:
        return self._parameters

    def run(self, parameters: Dict[str, Any]) -> str:
        result = self.method(**parameters)
        if result is None:
            return ""
        return str(result)
